encryption_mode: rsa
server:

  env: production
  secret_key: "RSA:xqJnz7S5xOEFQkUsOg2VuGvamJDlPqjhsqWCx4G6TORMgO+6orVzBG5v/9/tynCBy1fzfbbXwaQjv6wveLVJSJ3EmE4OJMduOHL2OdfhRLVEDK1RRF1BtgaFsk2RgIMOk8hubjJkyNgOA+4HjdTh3EbKFc3NrJqvn25Jw9VE2H+0eF45mrJD+YiFtyM7n5gj11l9a9oQM5SdgTT7Zpeildg87G13Sq7q/gjVY/7t0b2q9ixZxOVqcVWDr8ooZ0nv3jT0ntkxYBMFo3zLNwf96h3alCKQpzkmFi6hBRkfaEplqmFqDYxK+DRsmO156bmGaVlpnUxw1X+V1ps7vWb+9XWDdsRt3nKKQ2tdB3NUbT8hollLAjpXsWyKGJBGuVfJKPFp/gdOiF8WMoixBEu2Tfnl5gZXpg=="

  database:
    kind: "postgresql"
    hostname: "localhost:5432"
    username: "yueapp"
    password: "RSA:imyB5jlOh0PaQ6hKGULIeH4cWOmpjne+k1AWF0YOkHcTCX/2xGUT8eV4kZMF7LEglfncPBXqQ4f9KHsCjKgtZMwbnjhKYkmUacN2DlO2mq5KudbhOgfiFMreSz4k+nWg5SIRs9om8EqM52/IeKFWZwlWF1rRGn83JFt7At0LXVCFVxp+0/y8KJ/ki6ZIlFz2p+PRAVoCImUAaHspmJzH1A07xlPPmPCMVuXCk57PyWrqPnqzU78TQK28iFYp/xlD2gl/OhAAWXuha1JbuDUGM1i5fJ540/V76jxiy5vHRiNysiVbuUssiIKX1jU67T4KMw3TSHTMUfzBJnJ5EXur5ST4yd6idzpgybCMrqwBIRJwXlIZp6IyLqNMHPDZyKwyNGq8/mJ5sy8="
    database: "yueapp"

  logging:
    directory: "./logs"
    filename: "server.log"
    max_size: 2MB
    num_backups: 10
    level: info

  transcode:
    audio:
      bin_path: /usr/bin/ffmpeg
      tmp_path: /tmp/yue-audio
    image: {}

  aws:
    creds:
      endpoint: "https://nyc3.digitaloceanspaces.com"
      access_key: "RSA:uIBlJFdMhSwEhmnjVx/4B4YqxejUte6WgtOMjhXDg09aY3AL3SMxL44/IlNK8ulTfXF04DCscMprskzf4j+kgRJx4fnQB7yxYfrIyYhInxSd72Wy3uW5m3PbzUux2/jkb6XmtKiGzS0ZAGsiNnb1FSbrlxzWsfv4OIhXU16SsBc9pZKRofBeKn6CBd60TQYs9inkyBrDoY735Zp7MGGvQSHU9EwotPc2wlhafDSCzrWKQ1qVLTgmxmIIEcruvkiyF5ENyTdURq15Fe30qeZ/tI6ZEUVgpaLBbfbak8pqseO6ve7dYngTJ+owb4D1L6hbp0zUrwFJqFpNLlVPRXNes293C5vQoFAOTPYIvuK7/CtWO9Jp1cKuL4qoT9cEYSdKDc7hP2oO5TTqEpsvR7vzdYjy4hc="
      secret_key: "RSA:RDROtsi9Xb3dRnGNJi+dbDwIznM/2MzuaS7imDKQw2tx1ElhMjxsEaZRptXZ5sBnYVUox8SfSzWa4YbVwV+vlbIdiu/NQvocdpDEZKEW97nBlNjVj5bRwCaGcAikHz7voFc2ualZn1thZLMRDpjuVyzUAVMYL5TI9esuFcns5nK3gPYN6Uy0YExSOMO1Su7j7Thf4oOmzcxDYk0jQb5M78eKpOS3mX0vSgdU9boB0eUNVSytGTcwEUkOCkmAKNPK0JZH64V3xi9LabEsajg5EnQeqn6QNi+2ZaqASNnk/VaRZutivInECj07f9QKOGygtlTDWQD7d3USS5kbz0g3BIgCCcEYxuB35OOsdu43C9Oeduv6Q67y0A/mXjcttL1e+bqsITgyKGG8FJebR4OJOwMLRWM/fpf/a2kup3SrGpFOtojX/nu97uNMYQ=="
      region: nyc3
