export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';


export const TEST_MESSSAGE_CREATE = "TEST_MESSSAGE_CREATE"
export const TEST_MESSSAGE_DELETE = "TEST_MESSSAGE_DELETE"
export const TEST_MESSSAGE_GET_ALL = "TEST_MESSSAGE_GET_ALL"
export const TEST_MESSSAGE_SUCCESS = "TEST_MESSSAGE_SUCCESS"
export const TEST_MESSSAGE_FAILURE = "TEST_MESSSAGE_FAILURE"
export const TEST_RANDOM_INT = "TESET_RANDOM_INT"


export const QUEUE_GET = "QUEUE_GET"
export const QUEUE_GET_SUCCESS = "QUEUE_GET_SUCCESS"
export const QUEUE_GET_FAILURE = "QUEUE_GET_FAILURE"
export const QUEUE_POPULATE = "QUEUE_POPULATE"
export const QUEUE_POPULATE_SUCCESS = "QUEUE_POPULATE_SUCCESS"
export const QUEUE_POPULATE_FAILURE = "QUEUE_POPULATE_FAILURE"
export const QUEUE_SET = "QUEUE_SET"
export const QUEUE_SET_SUCCESS = "QUEUE_SET_SUCCESS"
export const QUEUE_SET_FAILURE = "QUEUE_SET_FAILURE"
