encryption_mode: none
server:

  build: ./frontend/build
  static: ./frontend/build/static

  host: 0.0.0.0
  port: 4200

  env: production
  secret_key: secret

  cors:
    origin: "*"

  database:
    kind: "sqlite"
    path: "database-dev.sqlite"

  ssl:
    # ssl is disabled so that the frontend can communicate
    # with the backend.
    private_key: ""
    certificate: ""

  logging:
    directory: "./logs"
    filename: "server.log"
    max_size: 2MB
    num_backups: 10
    level: debug

  transcode:
    audio:
      mode: ogg
      bin_path: /usr/bin/ffmpeg
      tmp_path: "/tmp/yue-audio"
    image: {}

