server:

  host: localhost
  port: 4200

  env: production
  secret_key: "secret"

  cors:
    origins: "*"

  database:
    kind: "postgresql"
    path: "localhost:5432"
    username: nsetzer
    password: password
    database: nsetzer

  ssl:
    # ssl is disabled so that the frontend can communicate
    # with the backend.
    private_key: ""
    certificate: ""

  logging:
    directory: "./logs"
    filename: "server.log"
    max_size: 2MB
    num_backups: 10
    level: debug

  filesystem:
    media_root: "/Users/nsetzer/Music/Library"
    other:
      test: "./test"
      mem: "mem://memtest"
      bucket: "s3://cogito-singletenantdev-recompute"

  transcode:
    audio:
      bin_path: /usr/local/bin/ffmpeg
      tmp_path: "/tmp/yue-audio"
    image: {}
