server:

  env: production
  secret_key: "secret"

  cors:
    origins: "*"

  database:
    kind: "sqlite"
    path: "database.sqlite"

  ssl:
    # ssl is disabled so that the frontend can communicate
    # with the backend.
    private_key: ""
    certificate: ""

  logging:
    directory: "./logs"
    filename: "server.log"
    max_size: 2MB
    num_backups: 10
    level: debug

  filesystem:
    media_root: "/mnt/data"

  transcode:
    audio:
      bin_path: /usr/bin/ffmpeg
    image: {}
