

FROM ubuntu:18.04

run apt-get update
run apt-get -y upgrade
run apt-get update
run apt-get install -y postgresql postgresql-contrib
run apt-get install -y python3 python3-pip
run apt-get install -y ffmpeg
run apt-get install -y nginx

