server:

  env: production
  secret_key: "secret"

  cors:
    origins: "*"

  database:
    kind: "sqlite"
    path: "database.sqlite"

  ssl:
    private_key: "config/production/selfsigned.key"
    certificate: "config/production/selfsigned.crt"

  logging:
    directory: "./logs"
    filename: "server.log"
    max_size: 2MB
    num_backups: 10
    level: debug

  filesystem:
    media_root: "D:\\Music"

  transcode:
    audio:
      bin_path: "C:\\ffmpeg\\bin\\ffmpeg.exe"
      tmp_path: "D:\\Music\\transcode"
    image: {}

