server:

  host: 0.0.0.0
  port: 4200

  env: production
  secret_key: "secret"

  cors:
    origins: "*"

  database:
    kind: "sqlite"
    path: "database.sqlite"

  ssl:
    #
    # sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    # -keyout selfsigned.key -out selfsigned.crt
    #
    private_key: "config/production/selfsigned.key"
    certificate: "config/production/selfsigned.crt"

  logging:
    directory: "./logs"
    filename: "server.log"
    max_size: 2MB
    num_backups: 10
    level: debug

  filesystem:
    media_root: "/mnt/Data/Music"

  transcode:
    audio:
      bin_path: /bin/ffmpeg
      tmp_path: /tmp/yue-audio
    image: {}

